### Login to Admin
POST http://localhost:3000/api/admin/sign_in
Content-Type: application/json

{
    "email": "miguel@test.com",
    "password": "abcdef"
}

### Create New Pizza
POST http://localhost:3000/api/admin/pizzas/new
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQzNjUyMzUsInN1YiI6MX0.hPcJ9HcKJhShyuDKLIQW10IS8vbxil3ey0ANPvKq7rk

{
    "name": "Frutti di Mare",
    "base": "Traditional",
    "sauce": "Tomato",
    "toppings" :{
        "Mozarella Cheese": 1,
        "Ham": 0,
        "Tomato": 1,
        "Bacon": 0,
        "Pineapple": 0,
        "Vegan Cheese": 0,
        "Pepperoni": 0,
        "Anchovies": 1,
        "Mushrooms": 0,
        "Prawns": 1,
        "BBQ Chicken": 0
    }

}

### Index pizzas
GET http://localhost:3000/api/pizzas/index
Content-Type: application/json

### Show product with ID: 1
GET http://localhost:3000/api/pizzas/1
Content-Type: application/json

### Show product with invalid ID
GET http://localhost:3000/api/pizzas/999
Content-Type: application/json

### Sucessfully update pizza 1
PUT http://localhost:3000/api/admin/pizzas/1 
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQzNjUyMzUsInN1YiI6MX0.hPcJ9HcKJhShyuDKLIQW10IS8vbxil3ey0ANPvKq7rk

{
    "name": "Frutti di Mare",
    "base": "Traditional",
    "sauce": "Tomato",
    "toppings" :{
        "Mozarella Cheese": 1,
        "Ham": 0,
        "Tomato": 1,
        "Bacon": 0,
        "Pineapple": 0,
        "Vegan Cheese": 0,
        "Pepperoni": 0,
        "Anchovies": 1,
        "Mushrooms": 0,
        "Prawns": 1,
        "BBQ Chicken": 0
    }

}

### Successfully Delete Product; While testing, if db has just been seeded, create a product first.

DELETE http://localhost:3000/api/admin/pizzas/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzE2MjAsInN1YiI6MX0.LhM56tAqXuX-OBIHY37pFEWmiEOdqTiz77XY0P5fpMQ