### Create User
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "name": "Ruan",
    "email": "ruanito@test.com",
    "password": "abcdef",
    "password_confirmation": "abcdef"
}

### Sign in || Correct details

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "ruanito@test.com",
    "password": "abcdef"
}

### Sign in || Incorrect password

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "ruanito@test.com",
    "password": "password"
}

### Sign in || Incorrect Email

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "nonexistent@test.com",
    "password": "abcdef"
}

### Update Password

PUT http://localhost:3000/api/auth/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDM5NDEwMzksInN1YiI6NX0.gZtbu2A478ZGtp_oBY1c2ePNJBQJl3634XaBTv7YibM

{
    "password": "password"
}

### Delete User

DELETE http://localhost:3000/api/auth/destroy
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDM5NDIyOTcsInN1YiI6N30.m0HyJjJJvvHOU76VDTvsJggIrejB7QASzXFGM40ER08

### Show Account Details

GET http://localhost:3000/api/auth/show
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDM5NDEzMDYsInN1YiI6Nn0.8quBOCQXOAxyKAhmL8M-EfNQ8GGZN7odJ3Wp_0K8um0