### Create User
POST http://localhost:3000/auth/sign_up
Content-Type: application/json

{
    "name": "Ruan",
    "email": "ruanito@test.com",
    "password": "abcdef",
    "password_confirmation": "abcdef"
}

### Sign in || Correct details

POST http://localhost:3000/auth/sign_in
Content-Type: application/json

{
    "email": "ruanito@test.com",
    "password": "abcdef"
}

### Sign in || Incorrect password

POST http://localhost:3000/auth/sign_in
Content-Type: application/json

{
    "email": "ruanito@test.com",
    "password": "password"
}

### Sign in || Incorrect Email

POST http://localhost:3000/auth/sign_in
Content-Type: application/json

{
    "email": "nonexistent@test.com",
    "password": "abcdef"
}

### Update Password

POST http://localhost:3000/auth/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDM5Mzc2NjksInN1YiI6Mn0.6J2pNxI0mpjAoXfxzPsgC2ESEaqxnBcIht-scEk4e7w

{
    "password": "password"
}