### Login to Admin
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "miguel@test.com",
    "password": "abcdef"
}

### Create New Lettuce Topping
POST http://localhost:3000/api/pizzas/new
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQwNDQ1MDEsInN1YiI6MX0.pLbnbqO1KW3QCpnJcYPMNkhK5ZX9dOaVWCHYSy3NE1A

{
    "name": "Frutti di Mare",
    "price": 4.20,
    "recipe": {
        "base": "Traditional",
        "sauce": "Tomato",
        "toppings" :{
            "Mozarella Cheese": 1,
            "Ham": 0,
            "Tomato": 1,
            "Bacon": 0,
            "Pineapple": 0,
            "Vegan Cheese": 0,
            "Pepperoni": 0,
            "Anchovies": 1,
            "Mushrooms": 0,
            "Prawns": 1,
            "BBQ Chicken": 0
        }
    }
}

### Index pizzas
GET http://localhost:3000/api/pizzas/index
Content-Type: application/json

### Show product with ID: 1
GET http://localhost:3000/api/pizzas/1
Content-Type: application/json

### Show product with invalid ID
GET http://localhost:3000/api/pizzas/999
Content-Type: application/json

### Sucessfully update product 1
PUT http://localhost:3000/api/pizzas/1 
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQwNDE3MTAsInN1YiI6MX0.LJey7fPxd-YFr-MQn6Dg_mjw0iqybcJVb_-V176qz1U

{
    "name": "Frutti di Mare",
    "price": 4.20,
    "recipe": {
        "base": "Traditional",
        "sauce": "Tomato",
        "toppings" :{
            "Mozarella Cheese": 1,
            "Ham": 0,
            "Tomato": 1,
            "Bacon": 0,
            "Pineapple": 0,
            "Vegan Cheese": 0,
            "Pepperoni": 0,
            "Anchovies": 1,
            "Mushrooms": 0,
            "Prawns": 1,
            "BBQ Chicken": 0
        }
    }
}

### Successfully Delete Product; While testing, if db has just been seeded, create a product first.

DELETE http://localhost:3000/api/pizzas/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQwNDQ3NTgsInN1YiI6MX0.fhgkNVYWm9H4vwAwHFl0OSqq9pSjLgZKfWu4xO0YR0w